version: '3'

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    ports: 
      - "8000:8000"

characters:
  gateway:
    container_name: characters
    restart: always
    build: ./characters
    ports: 
      - ":8001"

films:
  gateway:
    container_name: films
    restart: always
    build: ./films
    ports: 
      - ":8002"

planets:
  gateway:
    container_name: planets
    restart: always
    build: ./planets
    ports: 
      - ":8003"            

database:
  gateway:
    container_name: database
    restart: always
    build: ./database
    ports: 
      - ":8004"